### PR TITLE
Added consortium docs

### PR DESCRIPTION
**Pull request by RangerMauve**
Added some initial info about the Dat consortium as well as a document talking about my approach of doing facilitation for the calls.

Looking for feedback on the process, should it need more detail, any suggestions for what could be changed?

@dpaez @okdistribute  are ya'll still interested in facilitating some time soon? What do you think of this?

### CODE REVIEW

**Review by dpaez — APPROVED** [review]

**Comment by dpaez** [comment]
Hi @RangerMauve thanks for making this doc. I can help facilitating anytime soon. Over middle of March and 1st week of April, I'll be out. But besides that I'm always willing to help. My only concern is with the language, since English is not my mother-tongue sometimes the conversation can be a bit "rusty" 😅 but all in all I'll do my best.

**Comment by RangerMauve** [comment]
@dpaez You'll do fine! You've been doing great for the comm comm meetings so this should be a breeze. 😁 Would you be interested in doing next week on the 22nd?

**Comment by dpaez** [comment]
@RangerMauve alright, I'm in for the 22nd

**Comment by RangerMauve** [comment]
@dpaez Would you be up for sending the initial reminder email today or tomorrow? I could help out if you don't have time. 💜

**Comment by dpaez** [comment]
@RangerMauve  Yes, I was thinking to send those emails today.

**Pull request merged**
